//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Client { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> Finish_Date { get; set; }
        public Nullable<System.DateTime> Add_Date { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public Nullable<int> Category_ID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
