//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp19
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public string book_name { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<int> Category_id { get; set; }
        public Nullable<int> Author_id { get; set; }
        public Nullable<System.DateTime> Publish_date { get; set; }
    }
}
